### ISSUE TITLE
Need a Build.PL?

### ISSUE THREAD

**Issue by hyphaltip** [bioperl/Bio-PopGen#4]
@carandraug @cjfields do we need to have a Build.PL in each of these repos to enable a testing framework to work and install separately? 

I wasn't sure how the distributions are going to be built and separately sent to CPAN individually? Will this be scriptable in some massive way?

**Comment by cjfields** [comment]
They are using Dist::Zilla.  Might be worth a chat to go over specifics if you want to make releases

Sent from my iPhone

On Sep 13, 2018, at 1:25 PM, Jason Stajich <notifications@github.com<mailto:notifications@github.com>> wrote:


@carandraug<https://github.com/carandraug> @cjfields<https://github.com/cjfields> do we need to have a Build.PL in each of these repos to enable a testing framework to work and install separately?

I wasn't sure how the distributions are going to be built and separately sent to CPAN individually? Will this be scriptable in some massive way?

**Comment by carandraug** [comment]
More specificaly, we have our own  [Dist::Zilla::PluginBundle::BioPerl](https://metacpan.org/pod/Dist::Zilla::PluginBundle::BioPerl).  The configuration is the `dist`.ini`. If you have it installed, should be enough to do `dzil test` to run the tests.
